spring:
  application:
    name: PgVector_mcp
  ai:
    mcp:
      server:
        name: pgvector-mcp-server
        version: 1.0.0
        sse-endpoint: /api/v1/sse
        sse-message-endpoint: /api/v1/mcp
        capabilities:
          tool: true
        enabled: true
    # Spring AI Ollama 配置
    ollama:
      base-url: http://localhost:11434
      chat:
        model: qwen3:0.6b
        temperature: 0.7
      embedding:
        model: qwen3-embedding:0.6b

    # PgVector 向量存储配置
    vectorstore:
      pgvector:
        host: localhost
        port: 5434
        database: vectordb
        username: postgres
        password: postgres
        initialize-schema: true
        index-type: hnsw
        dimensions: 1024
        remove-existing-vector-store-table: false
        table-name: test_mcp

  # PostgreSQL 数据源配置
  datasource:
    url: jdbc:postgresql://localhost:5434/vectordb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  # JPA 配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

# 服务器端口配置
server:
  port: 8080

logging:
  level:
    io.modelcontextprotocol: TRACE
    org.springframework.ai.mcp: TRACE
